on: workflow_dispatch
name: Create Netlify site

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Get submodules
      run: |
        git submodule update --init --remote _external/data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install bundler and bundle install 
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Create Site
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_CMD: git submodule update --init --remote && bundle exec jekyll build --config '_config.yml,_config_staging.yml'
        NETLIFY_DIR: _site
        NETLIFY_BASE: /
